title: Blog site
author: pkadu
email: pranayvkadu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This will contain small stories.

# social links
twitter_username: pranay
github_username:  pkadu

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
